name: Build rust on windows
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: build
        run: cargo build
      - name: release
        uses: softprops/action-gh-release@v1
        # only do this step when there's a git tag
        if: startsWith(github.ref, 'refs/tags/')
          with:
          files: target/debug/demo.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
